### ISSUE TITLE
Prepare for internal and CRAN release

### ISSUE THREAD

**Issue by gmbecker** [insightsengineering/formatters#103]
- [x] coordinate with release plans for `rtables`
- [x] reverse dependency checks on exact release candidate commit
- [x] Final spot check of documentation including full read through
- [x] check with `--as-cran`
- [x] check in [win-builder](https://win-builder.r-project.org/)

**Comment by gmbecker** [comment]
@shajoezhu please fire off final reverse dependency checks for formatters based on the current head of main

**Comment by shajoezhu** [comment]
Thanks @gmbecker ! this is automatically ran daily 

@cicdguy @clarkliming for awareness. we are preping for formatters and rtables release

**Comment by gmbecker** [comment]
@shajoezhu where can I see the results of that?

**Comment by shajoezhu** [comment]
there is a gchat channel for this. i just added you :)
