### ISSUE TITLE
CRAN release of v0.4.0

### ISSUE THREAD

**Issue by gmbecker** [insightsengineering/formatters#111]
- [x] Submission to CRAN
- [x] Address any CRAN feedback
- [ ] Acceptance on CRAN
- [ ] Merge cran_submission_0.4.0 branch into main
- [ ] Tag release in github

**Comment by gmbecker** [comment]
CRAN found automated reverse dependency failures in rtables (because that version is over a year old and the formatters API has drifted it seems, since then). I have responded that a new version of rtables is coming which does not fail with the new formatters. Awaiting further response

**Comment by shajoezhu** [comment]
https://cran.r-project.org/web/packages/formatters/index.html

done

**Comment by shajoezhu** [comment]
thanks a lot Gabe!

**Comment by gmbecker** [comment]
This was not done but is complete now
