### ISSUE TITLE
HexSticker icon for formatters

### ISSUE THREAD

**Issue by shajoezhu** [insightsengineering/formatters#113]

**Comment by Melkiades** [comment]
Like is there any suggested style or principle? I have an idea eventually

**Comment by shajoezhu** [comment]
hey davide, something like

         ^
      /     \
    /          \
 /                \
|    xx.xx       |
|    xx.x%      |
| formatters |
\                 /
  \            /
    \        /
         v


would be sufficient, just nice and simple, capture 2 or 3 formats,

**Comment by gmbecker** [comment]
So this would cover the formatting part of formatters but not the rendering and pagination part, so I'm not sure if thats what we want or not

**Comment by Melkiades** [comment]
I was thinking about putting a stylized printer as a symbol with a table in it

**Comment by Melkiades** [comment]
[formatters.pdf](https://github.com/insightsengineering/formatters/files/11080664/formatters.pdf)
which is this:
![Screenshot 2023-03-27 180253](https://user-images.githubusercontent.com/11279768/227998181-ff75a547-341b-43c7-9831-852b9c20a699.png)

**Comment by Melkiades** [comment]
> Are there other NEST hex-logos that have a colored border like that? the one for `rtables` is white. If so, is the color being used in the border here used elsewhere within the NEST logo color pallete?

Other than that logo looks good

_Originally posted by @gmbecker in https://github.com/insightsengineering/rlistings/pull/79#pullrequestreview-1296448742_

Following up on this

**Comment by Melkiades** [comment]
version 2. I am for avoiding the shadow effect at al cost: [formatters (1).pdf](https://github.com/insightsengineering/formatters/files/11081404/formatters.1.pdf)
i.e.
![Screenshot 2023-03-27 191328](https://user-images.githubusercontent.com/11279768/228016464-b2af9750-1888-43b3-847a-ec3fbdd5a02a.png)

**Comment by shajoezhu** [comment]
this is brilliant! can you rotate the hex sticker 60 degress. i like the pink one, we have way too many dark color themed logos already.

**Comment by gmbecker** [comment]
The link is to insightsengineering.github.io/rtables

Is that intentional?

**Comment by Melkiades** [comment]
Thanks! Yes, it takes one min to rotate, my bad. The website is intentional but I could put anything there, I do not know what would be best. I personally prefer the salmon pink one, also no strong opinions about it.

@gmbecker you mean to put something like the current scaffold format in input and produce a table with known values? 42 and 3.14 ahah it could be cool but I think as it is now is a bit more synthetic which helps

**Comment by Melkiades** [comment]
[formatters (2).pdf](https://github.com/insightsengineering/formatters/files/11090957/formatters.2.pdf)

or the other colors?

**Comment by gmbecker** [comment]
Other way, I think, xx stuff on top, rendered values (ie numbers) on the bottom.

**Comment by Melkiades** [comment]
ok done there! Just to see the effect on the readme page. I think it works wonderfully now!
