### ISSUE TITLE
cran release 0.5.1

### ISSUE THREAD

**Issue by shajoezhu** [insightsengineering/formatters#159]
- [x] https://github.com/insightsengineering/formatters/pull/158
- [ ] https://github.com/insightsengineering/formatters/issues/143
- [ ] create cran_submission_0.5.1 branch
- [ ] Update version in description, update news
- [ ] tag v0.5.1
- [ ]  Submission to CRAN
- [ ]  Address any CRAN feedback
- [ ]  Acceptance on CRAN
- [ ]  Merge cran_submission_0.5.1 branch into main
- [ ]  Tag release in github

**Comment by gmbecker** [comment]
Through negotiation with CRAN I was able to get 0.5.0 onto CRAN despite the date-too-old check NOTE.
