### ISSUE TITLE
export_as_rtf lost indent

### ISSUE THREAD

**Issue by lchensigma** [insightsengineering/formatters#222]
**Summary**

when use export_as_rtf to output rtf with rtables, indents was lost.

```r

# your reproducible example here

```

**R session info**

```sh

# R -e "utils::sessionInfo()" output goes here

```

**OS / Environment**

- OS: [e.g. Windows 10, Ubuntu 20.04, Centos 8]
- Docker Image [e.g. rocker/verse:4.1.2]

**Comment by shajoezhu** [comment]
hi @lchensigma , can you provide us with a reproducible example? Thanks!

**Comment by Melkiades** [comment]
If I check the result of `export_as_rtf` from your example indentation is still present
![Screenshot 2024-01-18 145059](https://github.com/insightsengineering/formatters/assets/11279768/0cdbcef6-0556-44ea-9408-feefe777869b)

**Comment by lchensigma** [comment]
Thank you. I think it was fixed now.
