### ISSUE TITLE
rtables summarize_row_groups fails with export_as_txt

### ISSUE THREAD

**Issue by shajoezhu** [insightsengineering/formatters#233]
```R
basic_table() %>%
  split_rows_by("Species") %>%
  summarize_row_groups("Sepal.Length") %>%
  build_table(iris) %>%
  export_as_txt()
```

**Comment by gmbecker** [comment]
This table will not be paginatable, and pagination differences are the only meaningful reason to use `summarize_row_groups` instead of `analyze` within the deepest level of row splitting. I have trouble believing this is actually something someone correctly needs to do...
