### ISSUE TITLE
adding code of conduct

### ISSUE THREAD

**Issue by shajoezhu** [insightsengineering/formatters#238]
https://github.com/insightsengineering/rtables/blob/main/.github/CODE_OF_CONDUCT.md

**Comment by martincadek** [comment]
I need clarification on this, the COC is already in `rtables/.github/CODE_OF_CONDUCT.md`. It works as expected, i.e., a tab in GitHub and is also present in https://insightsengineering.github.io/rtables/latest-tag/CODE_OF_CONDUCT.html. What is precisely the request here please?

**Comment by martincadek** [comment]
PR here: https://github.com/insightsengineering/formatters/pull/268
