### ISSUE TITLE
duplicated page number

### ISSUE THREAD

**Issue by BFalquet** [insightsengineering/formatters#286]
pages number are duplicated when object takes more than one page.

```
library(chevron)
library(rtables)
res <- run(lbt01, chevron::syn_data)
withr::with_options(
  list(formatter_default_page_number = "{i}/{n}"),
  cat(export_as_txt(res))
)
```
<img width="442" alt="image" src="https://github.com/insightsengineering/formatters/assets/64274616/3d8ef6f0-9104-4755-94e8-0b19c5ff45b8">

In addition, the `page_num` argument duplicates again the page numbers.

```
withr::with_options(
  list(formatter_default_page_number = "{i}/{n}"),
  cat(export_as_txt(res), page_num = "- page {i} of {n} -")
)
```

<img width="436" alt="image" src="https://github.com/insightsengineering/formatters/assets/64274616/bc8ce59f-976f-4b76-a9f5-892a77be66e8">

**Comment by Melkiades** [comment]
@BFalquet add priority if you think we need a fast fix for this, it should not be too complex

**Comment by BFalquet** [comment]
@Melkiades , can't add the tag somehow, but yes, the leadership considers it a priority.
