### ISSUE TITLE
Figure out how to handle NAs in "(N=xx)" format (ie rtables column counts).

### ISSUE THREAD

**Issue by gmbecker** [insightsengineering/formatters#33]
Arose initially within Roche/rtables#341

**Comment by gmbecker** [comment]
Relevant to https://github.com/Roche/rtables/issues/341

So I have a local change which makes it so any time the value being formatted is all NAs (ie `all(is.na(x))` is `TRUE`), just the `na_str` is returned. 

This allows us to display "" (ie nothing) with `NA` colcounts, but it _is_ a breaking change, as previously we would get decorated `na_str` values in a number of cases, notably  including the column header format (`"(N=xx)"`), which assuming `na_str = "NA"`, would be formatted as `(N=NA)`. It also changes behavior for all the single number `<>%` formats  (e.g., `"xx.x%"`) , which currently are formatted to `NA%`.

Because it is a breaking change, a) I don't think it can be put into the imminent release, and b) we need to discuss if this is actually the right behavior, and important enough. @shajoezhu @Melkiades @waddella

**Comment by gmbecker** [comment]
The proposed fix for this has been reapplied, @shajoezhu please a) look at any breakages this may cause, and b) consider whether this is the desired behavior. We can discuss it at a meeting

**Comment by gmbecker** [comment]
> So the cases are 3:
> 
> 1. I do not add any format -> toString(x) [as before]
> 2. I do add a format but not `na_str` [changed]
> 
> ```r
> # Before
> format_value(NA, format = "xx.xx%") #> NA% 
> 
> # After
> format_value(NA, format = "xx.xx%") #> NA
> ```
> 
> 3. I do add a format with `na_str` [changed]
> 
> ```r
> # Before
> format_value(NA, format = "xx.xx%", na_str = "a") #> a% 
> 
> # After
> format_value(NA, format = "xx.xx%", na_str = "a") #> a
> ```
> 


This was a motivating factor for the change, as we have had people unhappy that the `%` was unavoidable (when only using label formats and not analysis function customization or custom format functions).

Note also that you can get the old behavior easily in this case with `na_str = "a%"`.

> I personally preferred the previous way of doing it, as having a format structure, even with only NAs in the data, can be potentially more informative than only the `na_str` value. On the other hand, you specify in the format that you want a specific `na_str`, so it is up to the user if this is defined only as such in the output. Nonetheless, checking the errors in tern#687 (mentioned above), the new formats are really not great when we have more than one number like in the following:
> 
> ```r
> format_value(c(NA, 1), format = "xx (xx%)", na_str = "a")
> #[1] "a (100%)"
> format_value(c(NA, NA), format = "xx (xx%)", na_str = "a")
> #[1] "a"
> ```

I have intended to do this for a while, but I now have a local change that allows `na_str` to be of the same length as the value (so you can specify different NA behavior by position). With this change, the proposal becomes the following (already coded this way but element-wise NA behavior wasn't supported previously):

If the value is all NAs, *and* `length(na_str)` is one, just that value is emitted. If `length(na_str) > 1`, you get behavior analogous to the previous behavior.

```
# (currently local changes only but I can commit after our discussion tomorrow)
> format_value(c(NA, NA), format = "xx (xx.x%)")
[1] "NA"
> format_value(c(NA, NA), format = "xx (xx.x%)", na_str = "a")
[1] "a"
> format_value(c(NA, NA), format = "xx (xx.x%)", na_str = c("a", "b"))
[1] "a (b%)"
```

One open question here is whether the above should give `"a (b)"` instead. This would be more flexible and you could still get the above output by simply doing `na_str = c("a", "b%")` instead. 

I'm leaning towards yes on the above question, but will wait to hear feedback.


> 
> I must add that this fixes rtables#341 (mentioned above) as can be seen from the following output taken from the same issue:
> 
> ```
>                    Y            N        rnd_diff
>                  (N=77)       (N=73)             
> -------------------------------------------------
> All                                              
>   is_aerial    41 (53.2%)   39 (53.4%)      2    
>   is_magical   39 (50.6%)   37 (50.7%)      3   
> ```
> 
> It is probably not feasible but my ideal solution to the `(N=-1)` problem would have been to be able to specify which columns should have colcounts applied. Something like `add_column_counts(cols = c(1, 2))` or with colnames.

This *may* be possible, though I suspect it will be more work than it sounds like to get everything to work right. I think this is largely a separate issue though, as we have heard feedback that, e.g.,

**Comment by Melkiades** [comment]
You are right. I changed my mind. I think the new printing is more elegant and it is usually only cluttering to have specifications of formats with only NAs (like `(NA- NA)` for ranges). Also, fixing the downstream dependencies, I did not encounter any situations in which it was mixed (e.g. `NA (75%)`, which makes little sense).

**Comment by Melkiades** [comment]
> The proposed fix for this has been reapplied, @shajoezhu please a) look at any breakages this may cause, and b) consider whether this is the desired behavior. We can discuss it at a meeting

I think we discussed this and current behavior complies with our needs and tests. Thank you very much!
