### ISSUE TITLE
Decimal alignment support

### ISSUE THREAD

**Issue by gmbecker** [insightsengineering/formatters#42]
Major constraint: all cells that have the "dot" alignment within a column will be aligned together, regardless of whether they are contiguous in row space or not. 

Without the above constraint this doesnt seem tractable as rtables columns (which will use this feature once it is in) are often not homogenous, but with it it should be doable.

**Comment by Melkiades** [comment]
more ample discussion on the topic here https://github.com/insightsengineering/formatters/issues/26

**Comment by Melkiades** [comment]
I just remembered also this discussion which can be relevant here: https://github.com/Roche/rtables/issues/218

**Comment by gmbecker** [comment]
For reference:

```
#Numbers:
12345.6
0.235678
6.7
9.26


## round 1: auto width
12345.6
    0.235678
    6.7
    9.26

## auto width is 12
"12345.6     "
"    0.235678"
"    6.7     "
"    9.26    "

## round 2: column width 16!!!

## align: dec-left
"12345.6         "
"    0.235678    "
"    6.7         "
"    9.26        "

## align: dec-right
"    12345.6     "
"        0.235678"
"        6.7     "
"        9.26    "

## align: dec-center
"  12345.6       "
"      0.235678  "
"      6.7       "
"      9.26      "

```
