### ISSUE TITLE
New line splitter for main title and footers

### ISSUE THREAD

**Issue by Melkiades** [insightsengineering/formatters#45]
This follows issue [rtables#388](https://github.com/Roche/rtables/issues/388) as it boils down to how the `MatrixPrintForm` object is manipulated in the `toString` dedicated function. I am unsure how this will reflect into other outputs such as pdfs and so on but I am supposing that it is anyway another postprocessing from this point. We need also to discuss what should be the normal behavior and which parameters should be propagated where.

**Comment by gmbecker** [comment]
Closing this issue, as it is complete. Problems with how we did it should be raised as new issues.
