### ISSUE TITLE
Missing suggested package dependencies

### ISSUE THREAD

**Issue by Melkiades** [insightsengineering/formatters#49]
```
checking package dependencies ... ERROR
Packages suggested but not available: 'huxtable', 'gt'
The suggested packages are required for a complete check.
```

This fails the pipeline on `enabler`. Any clue on how to fix this? @cicdguy @arkadiuszbeer

**Comment by cicdguy** [comment]
Yeah these aren't available on enableR. @arkadiuszbeer - can you add them to the image?

**Comment by gmbecker** [comment]
There is also a way to tell R CMD check not to fail on missing Suggests packages. Which is implemented is up to @cicdguy and/or the enableR team. 

As mentioned elsewhere, these suggests packages should be irrelevant to internal enableR users as they relate to RTF support.

**Comment by arkadiuszbeer** [comment]
`huxtable` and `gt` have been addd into enableR
