### ISSUE TITLE
Increase coverage to >90%

### ISSUE THREAD

**Issue by Melkiades** [insightsengineering/formatters#87]
I think it is relevant to have few more unit tests

**Comment by shajoezhu** [comment]
we need to prioritize now as it is currently too low to pass auto-validation

**Comment by pawelru** [comment]
In order to avoid such tasks in the future - can we introduce a hard threshold for PR to pass only if coverage is greater than X

**Comment by Melkiades** [comment]
> In order to avoid such tasks in the future - can we introduce a hard threshold for PR to pass only if coverage is greater than X

@cicdguy FYI

NB: many tests for complex tables are difficult to recreate (and prone to error due to changes in internals) in formatters as they need some functionalities from rtables (e.g. topleft, col hierarchy, and so on). This potentially needs a complexification of the internal function used by formatters tests: `basic_matrix_form()`

**Comment by pawelru** [comment]
> > In order to avoid such tasks in the future - can we introduce a hard threshold for PR to pass only if coverage is greater than X
> 
> @cicdguy FYI

Before we ask for implementation - do you think it's worth to do this?

**Comment by Melkiades** [comment]
> Before we ask for implementation - do you think it's worth to do this?

In general, for sure. This repo is a bit problematic yet for that imo. We need to get there first with the above caveat. Afterwards, we can/should introduce the minimum >90 cover for PRs. Btw this would not be tricky if we could call `rtables` in formatters' tests, but I do not know, it would not make sense dependency-wise...

**Comment by shajoezhu** [comment]
I am not sure if enforcing a hard threthold all the time is a good idea. I would like to turn this on and off from time to time. I think right now, rtables, rlistings and formatters are under heavy development. We are sequeezing in a lot of code in at the moment. I think when it becomes more stable, we can have this check always on

**Comment by gmbecker** [comment]
I'd say that once a threshold is reached we can enforced (or at least warn
via a non-mandatory to merge check) that prs don't reduce the coverage
below it. We already have a gh action which calculates the coverage
difference.

All of that will have to wait until the coverage is ther ein the first
place, though

**Comment by gmbecker** [comment]
> I am not sure if enforcing a hard threthold all the time is a good idea. I would like to turn this on and off from time to time. I think right now, rtables, rlistings and formatters are under heavy development. We are sequeezing in a lot of code in at the moment. I think when it becomes more stable, we can have this check always on

I'm not sure I agree with this reasoning. If a lot of code is being touched by a lot of different people who may not even know what eachother are doing then testing is more important.

If you're adding enough untested code to push the total coverage below the threshold, your PR isn't ready until you've added tests that ensure that the code changes are correct...

**Comment by shajoezhu** [comment]
Hi @gmbecker , thanks a lot for self-assiging this issue. Just want to check if this is something that the team could help as well. Between this task and preparing for training material, I believe preping the training for the team is more important. Thanks!

**Comment by gmbecker** [comment]
Formatters us more difficult to write tests for than other packages because
it mostly operates on things that are difficult yo construct by hand
(because they're built in other packages) which is why I am doing this one
myself. Also its nearly done at this point.

Best

**Comment by shajoezhu** [comment]
Thanks so much Gabe! Much appreicated!

**Comment by shajoezhu** [comment]
Hi @gmbecker , really appreciate the fast turn around. Can you branch off and raise PRs in the future please. Thanks

**Comment by gmbecker** [comment]
@shajoezhu this was closed by a PR, I no longer have the ability to commit directly to main

**Comment by shajoezhu** [comment]
Thanks a lot Gabe! Much appreciated!
